events {}

http {
    upstream app {
        server tic-blue:5000;
        # server tic-green:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }
    }
}